version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4
    container_name: softy-pinko-back-end-task4
    ports:
      - "5252:5252"
    restart: unless-stopped

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    container_name: softy-pinko-front-end-task4
    ports:
      - "9000:80"
    depends_on:
      - back-end
    restart: unless-stopped

networks:
  default:
    name: softy-pinko-network
