# Based on latest ubuntu
FROM ubuntu:latest

# Update package lists and upgrade installed software
RUN apt-get update && apt-get upgrade -y

# Set default command to echo "Hello, World!"
CMD ["echo", "Hello, World!"]
